### ISSUE TITLE
Plugin filter broken

### ISSUE THREAD

**Issue by Fred89** [dignajar/bludit#404]
Hi Diego,
For fix it go to default.css admin theme and correct the end file by this:
```css
#jsformplugin p {
	margin-bottom: 0;
}
/* ----------- PLUGINS FILTER ----------- */
tr.plugin-installed.hide, tr.plugin-notInstalled.hide{
  width:0%;
  opacity:0;
  display:none;
  transition:all 0.1s;
}
```
